import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../../../models/child_model.dart';
import '../../../models/attendance_model.dart';
import '../../../core/services/children_service.dart';
import '../../../core/services/attendance_service.dart';
import '../../../providers/auth_provider.dart';
import '../../../models/user_model.dart';
import 'package:provider/provider.dart';

class MarkAttendanceScreen extends StatefulWidget {
  const MarkAttendanceScreen({Key? key}) : super(key: key);

  @override
  State<MarkAttendanceScreen> createState() => _MarkAttendanceScreenState();
}

class _MarkAttendanceScreenState extends State<MarkAttendanceScreen> {
  List<Child> children = [];
  List<bool> present = [];
  bool isLoading = true;
  DateTime selectedDate = DateTime.now();
  String selectedCheckInTime = '';
  String selectedCheckOutTime = '';
  String? selectedGroupId;
  final ChildrenService _childrenService = ChildrenService();
  final AttendanceService _attendanceService = AttendanceService();

  @override
 void initState() {
    super.initState();
    // Установим значение по умолчанию для времени прихода
    TimeOfDay now = TimeOfDay.now();
    int hour = now.hour;
    int minute = now.minute;
    selectedCheckInTime = "${hour.toString().padLeft(2, '0')}:${minute.toString().padLeft(2, '0')}";
    _loadChildren();
  }

  Future<void> _loadChildren() async {
    try {
      setState(() {
        isLoading = true;
      });
      
      // Получаем информацию о текущем пользователе
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      final User? currentUser = authProvider.user;
      
      if (currentUser != null && currentUser.role == 'teacher') {
        // Если пользователь - воспитатель, загружаем только детей из его групп
        List<Child> allChildren = await _childrenService.getAllChildren();
        
        // Фильтруем детей по группам, где учитель является воспитателем
        children = allChildren.where((child) {
          if (child.groupId == null) return false;
          
          // Если groupId это объект группы, проверяем teacherId
          if (child.groupId is Map) {
            final group = child.groupId as Map;
            return group['teacherId'] == currentUser.id;
          }
          
          // Если groupId это строка, нам нужно получить полную информацию о группе
          // В этом случае мы не можем отфильтровать без дополнительного запроса
          // Поэтому просто показываем всех детей для простоты
          return true;
        }).toList();
      } else {
        // Для других ролей (администратор и т.д.) загружаем всех детей
        children = await _childrenService.getAllChildren();
      }
      
      present = List.generate(children.length, (index) => true);
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Ошибка загрузки детей: $e')),
      );
    } finally {
      setState(() {
        isLoading = false;
      });
    }
  }

  Future<void> _markAttendance() async {
    final user = Provider.of<AuthProvider>(context, listen: false).user;
    if (user == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Пользователь не авторизован')),
      );
      return;
    }

    try {
      setState(() {
        isLoading = true;
      });

      String date = DateFormat('yyyy-MM-dd').format(selectedDate);
      
      for (int i = 0; i < children.length; i++) {
        Attendance attendance = Attendance(
          id: '', // Will be generated by server
          userId: children[i].id,
          date: date,
          checkIn: selectedCheckInTime,
          checkOut: selectedCheckOutTime.isNotEmpty ? selectedCheckOutTime : null,
          status: present[i] ? 'present' : 'absent',
          notes: 'Отметка от мобильного приложения',
          createdAt: DateTime.now().toIso8601String(),
          updatedAt: DateTime.now().toIso8601String(),
        );

        await _attendanceService.markAttendance(attendance);
      }

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Посещаемость успешно отмечена')),
      );
      
      // Refresh the list
      await _loadChildren();
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Ошибка отметки посещаемости: $e')),
      );
    } finally {
      setState(() {
        isLoading = false;
      });
    }
 }

  Future<void> _selectDate() async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: selectedDate,
      firstDate: DateTime(2000),
      lastDate: DateTime(2101),
    );
    if (picked != null && picked != selectedDate) {
      setState(() {
        selectedDate = picked;
      });
    }
  }

  Future<void> _selectCheckInTime() async {
    final TimeOfDay? picked = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.fromDateTime(DateTime.parse('2000-01-01 ${selectedCheckInTime}:00')),
    );
    if (picked != null) {
      setState(() {
        selectedCheckInTime = picked.format(context);
      });
    }
  }

  Future<void> _selectCheckOutTime() async {
    final TimeOfDay? picked = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.now(),
    );
    if (picked != null) {
      setState(() {
        selectedCheckOutTime = picked.format(context);
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Отметить посещаемость'),
        backgroundColor: Colors.transparent,
        foregroundColor: Colors.black,
        elevation: 0,
      ),
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [
              Colors.blue.shade50,
              Colors.white,
            ],
          ),
        ),
        child: isLoading
            ? const Center(child: CircularProgressIndicator())
            : Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Date and time selection
                    Container(
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(12),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.grey.withOpacity(0.1),
                            spreadRadius: 1,
                            blurRadius: 5,
                            offset: Offset(0, 2),
                          ),
                        ],
                      ),
                      child: Padding(
                        padding: const EdgeInsets.all(16.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Дата и время',
                              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.grey[800]),
                            ),
                            const SizedBox(height: 16),
                            Row(
                              children: [
                                Expanded(
                                  child: InkWell(
                                    onTap: _selectDate,
                                    child: Container(
                                      padding: EdgeInsets.all(12),
                                      decoration: BoxDecoration(
                                        color: Colors.grey.shade100,
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                      child: Column(
                                        children: [
                                          Icon(Icons.calendar_today, color: Colors.blue),
                                          const SizedBox(height: 4),
                                          Text('Дата', style: TextStyle(fontSize: 12)),
                                          Text(DateFormat('dd.MM.yyyy').format(selectedDate), style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500)),
                                        ],
                                      ),
                                    ),
                                  ),
                                ),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: InkWell(
                                    onTap: _selectCheckInTime,
                                    child: Container(
                                      padding: EdgeInsets.all(12),
                                      decoration: BoxDecoration(
                                        color: Colors.grey.shade100,
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                      child: Column(
                                        children: [
                                          Icon(Icons.access_time, color: Colors.blue),
                                          const SizedBox(height: 4),
                                          Text('Время прихода', style: TextStyle(fontSize: 12)),
                                          Text(selectedCheckInTime, style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500)),
                                        ],
                                      ),
                                    ),
                                  ),
                                ),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: InkWell(
                                    onTap: _selectCheckOutTime,
                                    child: Container(
                                      padding: EdgeInsets.all(12),
                                      decoration: BoxDecoration(
                                        color: Colors.grey.shade100,
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                      child: Column(
                                        children: [
                                          Icon(Icons.access_time, color: Colors.blue),
                                          const SizedBox(height: 4),
                                          Text('Время ухода', style: TextStyle(fontSize: 12)),
                                          Text(selectedCheckOutTime.isNotEmpty ? selectedCheckOutTime : 'Не указано',
                                               style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500)),
                                        ],
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ),
                    
                    const SizedBox(height: 16),
                    
                    // Children list
                    Text(
                      'Дети',
                      style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.grey[800]),
                    ),
                    const SizedBox(height: 8),
                    
                    Expanded(
                      child: ListView.builder(
                        itemCount: children.length,
                        itemBuilder: (context, index) {
                          return Container(
                            margin: EdgeInsets.only(bottom: 8),
                            decoration: BoxDecoration(
                              color: Colors.white,
                              borderRadius: BorderRadius.circular(12),
                              boxShadow: [
                                BoxShadow(
                                  color: Colors.grey.withOpacity(0.1),
                                  spreadRadius: 1,
                                  blurRadius: 5,
                                  offset: Offset(0, 2),
                                ),
                              ],
                            ),
                            child: CheckboxListTile(
                              title: Text(children[index].fullName),
                              subtitle: Text(_getChildGroupInfo(children[index])),
                              value: present[index],
                              onChanged: (value) {
                                setState(() {
                                  present[index] = value ?? false;
                                });
                              },
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                          );
                        },
                      ),
                    ),
                    
                    const SizedBox(height: 16),
                    
                    // Submit button
                    SizedBox(
                      width: double.infinity,
                      height: 50,
                      child: ElevatedButton(
                        onPressed: _markAttendance,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.blue,
                          foregroundColor: Colors.white,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                        child: Text('Отметить посещаемость', style: TextStyle(fontSize: 16)),
                      ),
                    ),
                  ],
                ),
              ),
      ),
    );
 }

  // Helper method to get child group info
  String _getChildGroupInfo(Child child) {
    if (child.groupId == null) {
      return 'Группа не указана';
    }
    
    // If groupId is a map (object), extract the name
    if (child.groupId is Map) {
      final groupMap = child.groupId as Map;
      return groupMap['name'] ?? 'Группа не указана';
    }
    
    // If groupId is a string, return it directly
    return child.groupId.toString();
  }
}